package com.pittacode.romannumerals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.junit.jupiter.params.provider.Arguments.arguments;

class RomanConverterTest {

    private RomanConverter underTest;

    @BeforeEach
    void setUp() {
        underTest = new RomanConverter();
    }

    @ParameterizedTest
    @ValueSource(strings = {
            "A", "B", "E", "F", "G", "H",
            "J", "K", "N", "O", "P", "Q",
            "R", "S", "T", "U", "W", "Y", "Z"})
    void whenPasssingInvalidCharacter_throwException(String input) {
        assertThatThrownBy(() -> underTest.convert(input)).isInstanceOf(IllegalArgumentException.class);
    }

    @ParameterizedTest
    @MethodSource("romanNumeralsAndTheirValues")
    void romanNumeralInput_convertsToTheExpectedValue(String romanNumeral, int decimalValue) {
        var result = underTest.convert(romanNumeral);

        assertThat(result).isEqualTo(decimalValue);
    }

    private static Stream<Arguments> romanNumeralsAndTheirValues() {
        return Stream.of(
                arguments("I", 1),
                arguments("II", 2),
                arguments("III", 3),
                arguments("IV", 4),
                arguments("V", 5),
                arguments("VI", 6),
                arguments("VII", 7),
                arguments("VIII", 8),
                arguments("IX", 9),
                arguments("X", 10),

                arguments("XI", 11),
                arguments("XII", 12),
                arguments("XIII", 13),
                arguments("XIV", 14),
                arguments("XV", 15),
                arguments("XVI", 16),
                arguments("XVII", 17),
                arguments("XVIII", 18),
                arguments("XIX", 19),
                arguments("XX", 20),

                arguments("XXI", 21),
                arguments("XXII", 22),
                arguments("XXIII", 23),
                arguments("XXIV", 24),
                arguments("XXV", 25),
                arguments("XXVI", 26),
                arguments("XXVII", 27),
                arguments("XXVIII", 28),
                arguments("XXIX", 29),
                arguments("XXX", 30),

                arguments("XXXI", 31),
                arguments("XXXII", 32),
                arguments("XXXIII", 33),
                arguments("XXXIV", 34),
                arguments("XXXV", 35),
                arguments("XXXVI", 36),
                arguments("XXXVII", 37),
                arguments("XXXVIII", 38),
                arguments("XXXIX", 39),
                arguments("XL", 40),

                arguments("XLI", 41),
                arguments("XLII", 42),
                arguments("XLIII", 43),
                arguments("XLIV", 44),
                arguments("XLV", 45),
                arguments("XLVI", 46),
                arguments("XLVII", 47),
                arguments("XLVIII", 48),
                arguments("XLIX", 49),
                arguments("L", 50),

                arguments("LI", 51),
                arguments("LII", 52),
                arguments("LIII", 53),
                arguments("LIV", 54),
                arguments("LV", 55),
                arguments("LVI", 56),
                arguments("LVII", 57),
                arguments("LVIII", 58),
                arguments("LIX", 59),
                arguments("LX", 60),

                arguments("LXI", 61),
                arguments("LXII", 62),
                arguments("LXIII", 63),
                arguments("LXIV", 64),
                arguments("LXV", 65),
                arguments("LXVI", 66),
                arguments("LXVII", 67),
                arguments("LXVIII", 68),
                arguments("LXIX", 69),
                arguments("LXX", 70),

                arguments("LXXI", 71),
                arguments("LXXII", 72),
                arguments("LXXIII", 73),
                arguments("LXXIV", 74),
                arguments("LXXV", 75),
                arguments("LXXVI", 76),
                arguments("LXXVII", 77),
                arguments("LXXVIII", 78),
                arguments("LXXIX", 79),
                arguments("LXXX", 80),

                arguments("LXXXI", 81),
                arguments("LXXXII", 82),
                arguments("LXXXIII", 83),
                arguments("LXXXIV", 84),
                arguments("LXXXV", 85),
                arguments("LXXXVI", 86),
                arguments("LXXXVII", 87),
                arguments("LXXXVIII", 88),
                arguments("LXXXIX", 89),
                arguments("XC", 90),

                arguments("XCI", 91),
                arguments("XCII", 92),
                arguments("XCIII", 93),
                arguments("XCIV", 94),
                arguments("XCV", 95),
                arguments("XCVI", 96),
                arguments("XCVII", 97),
                arguments("XCVIII", 98),
                arguments("XCIX", 99),
                arguments("C", 100),

                arguments("CI", 101),
                arguments("CII", 102),
                arguments("CIII", 103),
                arguments("CIV", 104),
                arguments("CV", 105),
                arguments("CVI", 106),
                arguments("CVII", 107),
                arguments("CVIII", 108),
                arguments("CIX", 109),
                arguments("CX", 110),

                arguments("CXI", 111),
                arguments("CXII", 112),
                arguments("CXIII", 113),
                arguments("CXIV", 114),
                arguments("CXV", 115),
                arguments("CXVI", 116),
                arguments("CXVII", 117),
                arguments("CXVIII", 118),
                arguments("CXIX", 119),
                arguments("CXX", 120),

                arguments("CXXI", 121),
                arguments("CXXII", 122),
                arguments("CXXIII", 123),
                arguments("CXXIV", 124),
                arguments("CXXV", 125),
                arguments("CXXVI", 126),
                arguments("CXXVII", 127),
                arguments("CXXVIII", 128),
                arguments("CXXIX", 129),
                arguments("CXXX", 130),

                arguments("CXXXI", 131),
                arguments("CXXXII", 132),
                arguments("CXXXIII", 133),
                arguments("CXXXIV", 134),
                arguments("CXXXV", 135),
                arguments("CXXXVI", 136),
                arguments("CXXXVII", 137),
                arguments("CXXXVIII", 138),
                arguments("CXXXIX", 139),
                arguments("CXL", 140),

                arguments("CXLI", 141),
                arguments("CXLII", 142),
                arguments("CXLIII", 143),
                arguments("CXLIV", 144),
                arguments("CXLV", 145),
                arguments("CXLVI", 146),
                arguments("CXLVII", 147),
                arguments("CXLVIII", 148),
                arguments("CXLIX", 149),
                arguments("CL", 150),

                arguments("CLI", 151),
                arguments("CLII", 152),
                arguments("CLIII", 153),
                arguments("CLIV", 154),
                arguments("CLV", 155),
                arguments("CLVI", 156),
                arguments("CLVII", 157),
                arguments("CLVIII", 158),
                arguments("CLIX", 159),
                arguments("CLX", 160),

                arguments("CLXI", 161),
                arguments("CLXII", 162),
                arguments("CLXIII", 163),
                arguments("CLXIV", 164),
                arguments("CLXV", 165),
                arguments("CLXVI", 166),
                arguments("CLXVII", 167),
                arguments("CLXVIII", 168),
                arguments("CLXIX", 169),
                arguments("CLXX", 170),

                arguments("CLXXI", 171),
                arguments("CLXXII", 172),
                arguments("CLXXIII", 173),
                arguments("CLXXIV", 174),
                arguments("CLXXV", 175),
                arguments("CLXXVI", 176),
                arguments("CLXXVII", 177),
                arguments("CLXXVIII", 178),
                arguments("CLXXIX", 179),
                arguments("CLXXX", 180),

                arguments("CLXXXI", 181),
                arguments("CLXXXII", 182),
                arguments("CLXXXIII", 183),
                arguments("CLXXXIV", 184),
                arguments("CLXXXV", 185),
                arguments("CLXXXVI", 186),
                arguments("CLXXXVII", 187),
                arguments("CLXXXVIII", 188),
                arguments("CLXXXIX", 189),
                arguments("CXC", 190),

                arguments("CXCI", 191),
                arguments("CXCII", 192),
                arguments("CXCIII", 193),
                arguments("CXCIV", 194),
                arguments("CXCV", 195),
                arguments("CXCVI", 196),
                arguments("CXCVII", 197),
                arguments("CXCVIII", 198),
                arguments("CXCIX", 199),
                arguments("CC", 200),

                arguments("CCI", 201),
                arguments("CCII", 202),
                arguments("CCIII", 203),
                arguments("CCIV", 204),
                arguments("CCV", 205),
                arguments("CCVI", 206),
                arguments("CCVII", 207),
                arguments("CCVIII", 208),
                arguments("CCIX", 209),
                arguments("CCX", 210),

                arguments("CCXI", 211),
                arguments("CCXII", 212),
                arguments("CCXIII", 213),
                arguments("CCXIV", 214),
                arguments("CCXV", 215),
                arguments("CCXVI", 216),
                arguments("CCXVII", 217),
                arguments("CCXVIII", 218),
                arguments("CCXIX", 219),
                arguments("CCXX", 220),

                arguments("CCXXI", 221),
                arguments("CCXXII", 222),
                arguments("CCXXIII", 223),
                arguments("CCXXIV", 224),
                arguments("CCXXV", 225),
                arguments("CCXXVI", 226),
                arguments("CCXXVII", 227),
                arguments("CCXXVIII", 228),
                arguments("CCXXIX", 229),
                arguments("CCXXX", 230),

                arguments("CCXXXI", 231),
                arguments("CCXXXII", 232),
                arguments("CCXXXIII", 233),
                arguments("CCXXXIV", 234),
                arguments("CCXXXV", 235),
                arguments("CCXXXVI", 236),
                arguments("CCXXXVII", 237),
                arguments("CCXXXVIII", 238),
                arguments("CCXXXIX", 239),
                arguments("CCXL", 240),

                arguments("CCXLI", 241),
                arguments("CCXLII", 242),
                arguments("CCXLIII", 243),
                arguments("CCXLIV", 244),
                arguments("CCXLV", 245),
                arguments("CCXLVI", 246),
                arguments("CCXLVII", 247),
                arguments("CCXLVIII", 248),
                arguments("CCXLIX", 249),
                arguments("CCL", 250),

                arguments("CCLI", 251),
                arguments("CCLII", 252),
                arguments("CCLIII", 253),
                arguments("CCLIV", 254),
                arguments("CCLV", 255),
                arguments("CCLVI", 256),
                arguments("CCLVII", 257),
                arguments("CCLVIII", 258),
                arguments("CCLIX", 259),
                arguments("CCLX", 260),

                arguments("CCLXI", 261),
                arguments("CCLXII", 262),
                arguments("CCLXIII", 263),
                arguments("CCLXIV", 264),
                arguments("CCLXV", 265),
                arguments("CCLXVI", 266),
                arguments("CCLXVII", 267),
                arguments("CCLXVIII", 268),
                arguments("CCLXIX", 269),
                arguments("CCLXX", 270),

                arguments("CCLXXI", 271),
                arguments("CCLXXII", 272),
                arguments("CCLXXIII", 273),
                arguments("CCLXXIV", 274),
                arguments("CCLXXV", 275),
                arguments("CCLXXVI", 276),
                arguments("CCLXXVII", 277),
                arguments("CCLXXVIII", 278),
                arguments("CCLXXIX", 279),
                arguments("CCLXXX", 280),

                arguments("CCLXXXI", 281),
                arguments("CCLXXXII", 282),
                arguments("CCLXXXIII", 283),
                arguments("CCLXXXIV", 284),
                arguments("CCLXXXV", 285),
                arguments("CCLXXXVI", 286),
                arguments("CCLXXXVII", 287),
                arguments("CCLXXXVIII", 288),
                arguments("CCLXXXIX", 289),
                arguments("CCXC", 290),

                arguments("CCXCI", 291),
                arguments("CCXCII", 292),
                arguments("CCXCIII", 293),
                arguments("CCXCIV", 294),
                arguments("CCXCV", 295),
                arguments("CCXCVI", 296),
                arguments("CCXCVII", 297),
                arguments("CCXCVIII", 298),
                arguments("CCXCIX", 299),
                arguments("CCC", 300),

                arguments("CCCI", 301),
                arguments("CCCII", 302),
                arguments("CCCIII", 303),
                arguments("CCCIV", 304),
                arguments("CCCV", 305),
                arguments("CCCVI", 306),
                arguments("CCCVII", 307),
                arguments("CCCVIII", 308),
                arguments("CCCIX", 309),
                arguments("CCCX", 310),

                arguments("CCCXI", 311),
                arguments("CCCXII", 312),
                arguments("CCCXIII", 313),
                arguments("CCCXIV", 314),
                arguments("CCCXV", 315),
                arguments("CCCXVI", 316),
                arguments("CCCXVII", 317),
                arguments("CCCXVIII", 318),
                arguments("CCCXIX", 319),
                arguments("CCCXX", 320),

                arguments("CCCXXI", 321),
                arguments("CCCXXII", 322),
                arguments("CCCXXIII", 323),
                arguments("CCCXXIV", 324),
                arguments("CCCXXV", 325),
                arguments("CCCXXVI", 326),
                arguments("CCCXXVII", 327),
                arguments("CCCXXVIII", 328),
                arguments("CCCXXIX", 329),
                arguments("CCCXXX", 330),

                arguments("CCCXXXI", 331),
                arguments("CCCXXXII", 332),
                arguments("CCCXXXIII", 333),
                arguments("CCCXXXIV", 334),
                arguments("CCCXXXV", 335),
                arguments("CCCXXXVI", 336),
                arguments("CCCXXXVII", 337),
                arguments("CCCXXXVIII", 338),
                arguments("CCCXXXIX", 339),
                arguments("CCCXL", 340),

                arguments("CCCXLI", 341),
                arguments("CCCXLII", 342),
                arguments("CCCXLIII", 343),
                arguments("CCCXLIV", 344),
                arguments("CCCXLV", 345),
                arguments("CCCXLVI", 346),
                arguments("CCCXLVII", 347),
                arguments("CCCXLVIII", 348),
                arguments("CCCXLIX", 349),
                arguments("CCCL", 350),

                arguments("CCCLI", 351),
                arguments("CCCLII", 352),
                arguments("CCCLIII", 353),
                arguments("CCCLIV", 354),
                arguments("CCCLV", 355),
                arguments("CCCLVI", 356),
                arguments("CCCLVII", 357),
                arguments("CCCLVIII", 358),
                arguments("CCCLIX", 359),
                arguments("CCCLX", 360),

                arguments("CCCLXI", 361),
                arguments("CCCLXII", 362),
                arguments("CCCLXIII", 363),
                arguments("CCCLXIV", 364),
                arguments("CCCLXV", 365),
                arguments("CCCLXVI", 366),
                arguments("CCCLXVII", 367),
                arguments("CCCLXVIII", 368),
                arguments("CCCLXIX", 369),
                arguments("CCCLXX", 370),

                arguments("CCCLXXI", 371),
                arguments("CCCLXXII", 372),
                arguments("CCCLXXIII", 373),
                arguments("CCCLXXIV", 374),
                arguments("CCCLXXV", 375),
                arguments("CCCLXXVI", 376),
                arguments("CCCLXXVII", 377),
                arguments("CCCLXXVIII", 378),
                arguments("CCCLXXIX", 379),
                arguments("CCCLXXX", 380),

                arguments("CCCLXXXI", 381),
                arguments("CCCLXXXII", 382),
                arguments("CCCLXXXIII", 383),
                arguments("CCCLXXXIV", 384),
                arguments("CCCLXXXV", 385),
                arguments("CCCLXXXVI", 386),
                arguments("CCCLXXXVII", 387),
                arguments("CCCLXXXVIII", 388),
                arguments("CCCLXXXIX", 389),
                arguments("CCCXC", 390),

                arguments("CCCXCI", 391),
                arguments("CCCXCII", 392),
                arguments("CCCXCIII", 393),
                arguments("CCCXCIV", 394),
                arguments("CCCXCV", 395),
                arguments("CCCXCVI", 396),
                arguments("CCCXCVII", 397),
                arguments("CCCXCVIII", 398),
                arguments("CCCXCIX", 399),
                arguments("CD", 400),

                arguments("CDI", 401),
                arguments("CDII", 402),
                arguments("CDIII", 403),
                arguments("CDIV", 404),
                arguments("CDV", 405),
                arguments("CDVI", 406),
                arguments("CDVII", 407),
                arguments("CDVIII", 408),
                arguments("CDIX", 409),
                arguments("CDX", 410),

                arguments("CDXI", 411),
                arguments("CDXII", 412),
                arguments("CDXIII", 413),
                arguments("CDXIV", 414),
                arguments("CDXV", 415),
                arguments("CDXVI", 416),
                arguments("CDXVII", 417),
                arguments("CDXVIII", 418),
                arguments("CDXIX", 419),
                arguments("CDXX", 420),

                arguments("CDXXI", 421),
                arguments("CDXXII", 422),
                arguments("CDXXIII", 423),
                arguments("CDXXIV", 424),
                arguments("CDXXV", 425),
                arguments("CDXXVI", 426),
                arguments("CDXXVII", 427),
                arguments("CDXXVIII", 428),
                arguments("CDXXIX", 429),
                arguments("CDXXX", 430),

                arguments("CDXXXI", 431),
                arguments("CDXXXII", 432),
                arguments("CDXXXIII", 433),
                arguments("CDXXXIV", 434),
                arguments("CDXXXV", 435),
                arguments("CDXXXVI", 436),
                arguments("CDXXXVII", 437),
                arguments("CDXXXVIII", 438),
                arguments("CDXXXIX", 439),
                arguments("CDXL", 440),

                arguments("CDXLI", 441),
                arguments("CDXLII", 442),
                arguments("CDXLIII", 443),
                arguments("CDXLIV", 444),
                arguments("CDXLV", 445),
                arguments("CDXLVI", 446),
                arguments("CDXLVII", 447),
                arguments("CDXLVIII", 448),
                arguments("CDXLIX", 449),
                arguments("CDL", 450),

                arguments("CDLI", 451),
                arguments("CDLII", 452),
                arguments("CDLIII", 453),
                arguments("CDLIV", 454),
                arguments("CDLV", 455),
                arguments("CDLVI", 456),
                arguments("CDLVII", 457),
                arguments("CDLVIII", 458),
                arguments("CDLIX", 459),
                arguments("CDLX", 460),

                arguments("CDLXI", 461),
                arguments("CDLXII", 462),
                arguments("CDLXIII", 463),
                arguments("CDLXIV", 464),
                arguments("CDLXV", 465),
                arguments("CDLXVI", 466),
                arguments("CDLXVII", 467),
                arguments("CDLXVIII", 468),
                arguments("CDLXIX", 469),
                arguments("CDLXX", 470),

                arguments("CDLXXI", 471),
                arguments("CDLXXII", 472),
                arguments("CDLXXIII", 473),
                arguments("CDLXXIV", 474),
                arguments("CDLXXV", 475),
                arguments("CDLXXVI", 476),
                arguments("CDLXXVII", 477),
                arguments("CDLXXVIII", 478),
                arguments("CDLXXIX", 479),
                arguments("CDLXXX", 480),

                arguments("CDLXXXI", 481),
                arguments("CDLXXXII", 482),
                arguments("CDLXXXIII", 483),
                arguments("CDLXXXIV", 484),
                arguments("CDLXXXV", 485),
                arguments("CDLXXXVI", 486),
                arguments("CDLXXXVII", 487),
                arguments("CDLXXXVIII", 488),
                arguments("CDLXXXIX", 489),
                arguments("CDXC", 490),

                arguments("CDXCI", 491),
                arguments("CDXCII", 492),
                arguments("CDXCIII", 493),
                arguments("CDXCIV", 494),
                arguments("CDXCV", 495),
                arguments("CDXCVI", 496),
                arguments("CDXCVII", 497),
                arguments("CDXCVIII", 498),
                arguments("CDXCIX", 499),
                arguments("D", 500),

                arguments("DI", 501),
                arguments("DII", 502),
                arguments("DIII", 503),
                arguments("DIV", 504),
                arguments("DV", 505),
                arguments("DVI", 506),
                arguments("DVII", 507),
                arguments("DVIII", 508),
                arguments("DIX", 509),
                arguments("DX", 510),

                arguments("DXI", 511),
                arguments("DXII", 512),
                arguments("DXIII", 513),
                arguments("DXIV", 514),
                arguments("DXV", 515),
                arguments("DXVI", 516),
                arguments("DXVII", 517),
                arguments("DXVIII", 518),
                arguments("DXIX", 519),
                arguments("DXX", 520),

                arguments("DXXI", 521),
                arguments("DXXII", 522),
                arguments("DXXIII", 523),
                arguments("DXXIV", 524),
                arguments("DXXV", 525),
                arguments("DXXVI", 526),
                arguments("DXXVII", 527),
                arguments("DXXVIII", 528),
                arguments("DXXIX", 529),
                arguments("DXXX", 530),

                arguments("DXXXI", 531),
                arguments("DXXXII", 532),
                arguments("DXXXIII", 533),
                arguments("DXXXIV", 534),
                arguments("DXXXV", 535),
                arguments("DXXXVI", 536),
                arguments("DXXXVII", 537),
                arguments("DXXXVIII", 538),
                arguments("DXXXIX", 539),
                arguments("DXL", 540),

                arguments("DXLI", 541),
                arguments("DXLII", 542),
                arguments("DXLIII", 543),
                arguments("DXLIV", 544),
                arguments("DXLV", 545),
                arguments("DXLVI", 546),
                arguments("DXLVII", 547),
                arguments("DXLVIII", 548),
                arguments("DXLIX", 549),
                arguments("DL", 550),

                arguments("DLI", 551),
                arguments("DLII", 552),
                arguments("DLIII", 553),
                arguments("DLIV", 554),
                arguments("DLV", 555),
                arguments("DLVI", 556),
                arguments("DLVII", 557),
                arguments("DLVIII", 558),
                arguments("DLIX", 559),
                arguments("DLX", 560),

                arguments("DLXI", 561),
                arguments("DLXII", 562),
                arguments("DLXIII", 563),
                arguments("DLXIV", 564),
                arguments("DLXV", 565),
                arguments("DLXVI", 566),
                arguments("DLXVII", 567),
                arguments("DLXVIII", 568),
                arguments("DLXIX", 569),
                arguments("DLXX", 570),

                arguments("DLXXI", 571),
                arguments("DLXXII", 572),
                arguments("DLXXIII", 573),
                arguments("DLXXIV", 574),
                arguments("DLXXV", 575),
                arguments("DLXXVI", 576),
                arguments("DLXXVII", 577),
                arguments("DLXXVIII", 578),
                arguments("DLXXIX", 579),
                arguments("DLXXX", 580),

                arguments("DLXXXI", 581),
                arguments("DLXXXII", 582),
                arguments("DLXXXIII", 583),
                arguments("DLXXXIV", 584),
                arguments("DLXXXV", 585),
                arguments("DLXXXVI", 586),
                arguments("DLXXXVII", 587),
                arguments("DLXXXVIII", 588),
                arguments("DLXXXIX", 589),
                arguments("DXC", 590),

                arguments("DXCI", 591),
                arguments("DXCII", 592),
                arguments("DXCIII", 593),
                arguments("DXCIV", 594),
                arguments("DXCV", 595),
                arguments("DXCVI", 596),
                arguments("DXCVII", 597),
                arguments("DXCVIII", 598),
                arguments("DXCIX", 599),
                arguments("DC", 600),

                arguments("DCI", 601),
                arguments("DCII", 602),
                arguments("DCIII", 603),
                arguments("DCIV", 604),
                arguments("DCV", 605),
                arguments("DCVI", 606),
                arguments("DCVII", 607),
                arguments("DCVIII", 608),
                arguments("DCIX", 609),
                arguments("DCX", 610),

                arguments("DCXI", 611),
                arguments("DCXII", 612),
                arguments("DCXIII", 613),
                arguments("DCXIV", 614),
                arguments("DCXV", 615),
                arguments("DCXVI", 616),
                arguments("DCXVII", 617),
                arguments("DCXVIII", 618),
                arguments("DCXIX", 619),
                arguments("DCXX", 620),

                arguments("DCXXI", 621),
                arguments("DCXXII", 622),
                arguments("DCXXIII", 623),
                arguments("DCXXIV", 624),
                arguments("DCXXV", 625),
                arguments("DCXXVI", 626),
                arguments("DCXXVII", 627),
                arguments("DCXXVIII", 628),
                arguments("DCXXIX", 629),
                arguments("DCXXX", 630),

                arguments("DCXXXI", 631),
                arguments("DCXXXII", 632),
                arguments("DCXXXIII", 633),
                arguments("DCXXXIV", 634),
                arguments("DCXXXV", 635),
                arguments("DCXXXVI", 636),
                arguments("DCXXXVII", 637),
                arguments("DCXXXVIII", 638),
                arguments("DCXXXIX", 639),
                arguments("DCXL", 640),

                arguments("DCXLI", 641),
                arguments("DCXLII", 642),
                arguments("DCXLIII", 643),
                arguments("DCXLIV", 644),
                arguments("DCXLV", 645),
                arguments("DCXLVI", 646),
                arguments("DCXLVII", 647),
                arguments("DCXLVIII", 648),
                arguments("DCXLIX", 649),
                arguments("DCL", 650),

                arguments("DCLI", 651),
                arguments("DCLII", 652),
                arguments("DCLIII", 653),
                arguments("DCLIV", 654),
                arguments("DCLV", 655),
                arguments("DCLVI", 656),
                arguments("DCLVII", 657),
                arguments("DCLVIII", 658),
                arguments("DCLIX", 659),
                arguments("DCLX", 660),

                arguments("DCLXI", 661),
                arguments("DCLXII", 662),
                arguments("DCLXIII", 663),
                arguments("DCLXIV", 664),
                arguments("DCLXV", 665),
                arguments("DCLXVI", 666),
                arguments("DCLXVII", 667),
                arguments("DCLXVIII", 668),
                arguments("DCLXIX", 669),
                arguments("DCLXX", 670),

                arguments("DCLXXI", 671),
                arguments("DCLXXII", 672),
                arguments("DCLXXIII", 673),
                arguments("DCLXXIV", 674),
                arguments("DCLXXV", 675),
                arguments("DCLXXVI", 676),
                arguments("DCLXXVII", 677),
                arguments("DCLXXVIII", 678),
                arguments("DCLXXIX", 679),
                arguments("DCLXXX", 680),

                arguments("DCLXXXI", 681),
                arguments("DCLXXXII", 682),
                arguments("DCLXXXIII", 683),
                arguments("DCLXXXIV", 684),
                arguments("DCLXXXV", 685),
                arguments("DCLXXXVI", 686),
                arguments("DCLXXXVII", 687),
                arguments("DCLXXXVIII", 688),
                arguments("DCLXXXIX", 689),
                arguments("DCXC", 690),

                arguments("DCXCI", 691),
                arguments("DCXCII", 692),
                arguments("DCXCIII", 693),
                arguments("DCXCIV", 694),
                arguments("DCXCV", 695),
                arguments("DCXCVI", 696),
                arguments("DCXCVII", 697),
                arguments("DCXCVIII", 698),
                arguments("DCXCIX", 699),
                arguments("DCC", 700),

                arguments("DCCI", 701),
                arguments("DCCII", 702),
                arguments("DCCIII", 703),
                arguments("DCCIV", 704),
                arguments("DCCV", 705),
                arguments("DCCVI", 706),
                arguments("DCCVII", 707),
                arguments("DCCVIII", 708),
                arguments("DCCIX", 709),
                arguments("DCCX", 710),

                arguments("DCCXI", 711),
                arguments("DCCXII", 712),
                arguments("DCCXIII", 713),
                arguments("DCCXIV", 714),
                arguments("DCCXV", 715),
                arguments("DCCXVI", 716),
                arguments("DCCXVII", 717),
                arguments("DCCXVIII", 718),
                arguments("DCCXIX", 719),
                arguments("DCCXX", 720),

                arguments("DCCXXI", 721),
                arguments("DCCXXII", 722),
                arguments("DCCXXIII", 723),
                arguments("DCCXXIV", 724),
                arguments("DCCXXV", 725),
                arguments("DCCXXVI", 726),
                arguments("DCCXXVII", 727),
                arguments("DCCXXVIII", 728),
                arguments("DCCXXIX", 729),
                arguments("DCCXXX", 730),

                arguments("DCCXXXI", 731),
                arguments("DCCXXXII", 732),
                arguments("DCCXXXIII", 733),
                arguments("DCCXXXIV", 734),
                arguments("DCCXXXV", 735),
                arguments("DCCXXXVI", 736),
                arguments("DCCXXXVII", 737),
                arguments("DCCXXXVIII", 738),
                arguments("DCCXXXIX", 739),
                arguments("DCCXL", 740),

                arguments("DCCXLI", 741),
                arguments("DCCXLII", 742),
                arguments("DCCXLIII", 743),
                arguments("DCCXLIV", 744),
                arguments("DCCXLV", 745),
                arguments("DCCXLVI", 746),
                arguments("DCCXLVII", 747),
                arguments("DCCXLVIII", 748),
                arguments("DCCXLIX", 749),
                arguments("DCCL", 750),

                arguments("DCCLI", 751),
                arguments("DCCLII", 752),
                arguments("DCCLIII", 753),
                arguments("DCCLIV", 754),
                arguments("DCCLV", 755),
                arguments("DCCLVI", 756),
                arguments("DCCLVII", 757),
                arguments("DCCLVIII", 758),
                arguments("DCCLIX", 759),
                arguments("DCCLX", 760),

                arguments("DCCLXI", 761),
                arguments("DCCLXII", 762),
                arguments("DCCLXIII", 763),
                arguments("DCCLXIV", 764),
                arguments("DCCLXV", 765),
                arguments("DCCLXVI", 766),
                arguments("DCCLXVII", 767),
                arguments("DCCLXVIII", 768),
                arguments("DCCLXIX", 769),
                arguments("DCCLXX", 770),

                arguments("DCCLXXI", 771),
                arguments("DCCLXXII", 772),
                arguments("DCCLXXIII", 773),
                arguments("DCCLXXIV", 774),
                arguments("DCCLXXV", 775),
                arguments("DCCLXXVI", 776),
                arguments("DCCLXXVII", 777),
                arguments("DCCLXXVIII", 778),
                arguments("DCCLXXIX", 779),
                arguments("DCCLXXX", 780),

                arguments("DCCLXXXI", 781),
                arguments("DCCLXXXII", 782),
                arguments("DCCLXXXIII", 783),
                arguments("DCCLXXXIV", 784),
                arguments("DCCLXXXV", 785),
                arguments("DCCLXXXVI", 786),
                arguments("DCCLXXXVII", 787),
                arguments("DCCLXXXVIII", 788),
                arguments("DCCLXXXIX", 789),
                arguments("DCCXC", 790),

                arguments("DCCXCI", 791),
                arguments("DCCXCII", 792),
                arguments("DCCXCIII", 793),
                arguments("DCCXCIV", 794),
                arguments("DCCXCV", 795),
                arguments("DCCXCVI", 796),
                arguments("DCCXCVII", 797),
                arguments("DCCXCVIII", 798),
                arguments("DCCXCIX", 799),
                arguments("DCCC", 800),

                arguments("DCCCI", 801),
                arguments("DCCCII", 802),
                arguments("DCCCIII", 803),
                arguments("DCCCIV", 804),
                arguments("DCCCV", 805),
                arguments("DCCCVI", 806),
                arguments("DCCCVII", 807),
                arguments("DCCCVIII", 808),
                arguments("DCCCIX", 809),
                arguments("DCCCX", 810),

                arguments("DCCCXI", 811),
                arguments("DCCCXII", 812),
                arguments("DCCCXIII", 813),
                arguments("DCCCXIV", 814),
                arguments("DCCCXV", 815),
                arguments("DCCCXVI", 816),
                arguments("DCCCXVII", 817),
                arguments("DCCCXVIII", 818),
                arguments("DCCCXIX", 819),
                arguments("DCCCXX", 820),

                arguments("DCCCXXI", 821),
                arguments("DCCCXXII", 822),
                arguments("DCCCXXIII", 823),
                arguments("DCCCXXIV", 824),
                arguments("DCCCXXV", 825),
                arguments("DCCCXXVI", 826),
                arguments("DCCCXXVII", 827),
                arguments("DCCCXXVIII", 828),
                arguments("DCCCXXIX", 829),
                arguments("DCCCXXX", 830),

                arguments("DCCCXXXI", 831),
                arguments("DCCCXXXII", 832),
                arguments("DCCCXXXIII", 833),
                arguments("DCCCXXXIV", 834),
                arguments("DCCCXXXV", 835),
                arguments("DCCCXXXVI", 836),
                arguments("DCCCXXXVII", 837),
                arguments("DCCCXXXVIII", 838),
                arguments("DCCCXXXIX", 839),
                arguments("DCCCXL", 840),

                arguments("DCCCXLI", 841),
                arguments("DCCCXLII", 842),
                arguments("DCCCXLIII", 843),
                arguments("DCCCXLIV", 844),
                arguments("DCCCXLV", 845),
                arguments("DCCCXLVI", 846),
                arguments("DCCCXLVII", 847),
                arguments("DCCCXLVIII", 848),
                arguments("DCCCXLIX", 849),
                arguments("DCCCL", 850),

                arguments("DCCCLI", 851),
                arguments("DCCCLII", 852),
                arguments("DCCCLIII", 853),
                arguments("DCCCLIV", 854),
                arguments("DCCCLV", 855),
                arguments("DCCCLVI", 856),
                arguments("DCCCLVII", 857),
                arguments("DCCCLVIII", 858),
                arguments("DCCCLIX", 859),
                arguments("DCCCLX", 860),

                arguments("DCCCLXI", 861),
                arguments("DCCCLXII", 862),
                arguments("DCCCLXIII", 863),
                arguments("DCCCLXIV", 864),
                arguments("DCCCLXV", 865),
                arguments("DCCCLXVI", 866),
                arguments("DCCCLXVII", 867),
                arguments("DCCCLXVIII", 868),
                arguments("DCCCLXIX", 869),
                arguments("DCCCLXX", 870),

                arguments("DCCCLXXI", 871),
                arguments("DCCCLXXII", 872),
                arguments("DCCCLXXIII", 873),
                arguments("DCCCLXXIV", 874),
                arguments("DCCCLXXV", 875),
                arguments("DCCCLXXVI", 876),
                arguments("DCCCLXXVII", 877),
                arguments("DCCCLXXVIII", 878),
                arguments("DCCCLXXIX", 879),
                arguments("DCCCLXXX", 880),

                arguments("DCCCLXXXI", 881),
                arguments("DCCCLXXXII", 882),
                arguments("DCCCLXXXIII", 883),
                arguments("DCCCLXXXIV", 884),
                arguments("DCCCLXXXV", 885),
                arguments("DCCCLXXXVI", 886),
                arguments("DCCCLXXXVII", 887),
                arguments("DCCCLXXXVIII", 888),
                arguments("DCCCLXXXIX", 889),
                arguments("DCCCXC", 890),

                arguments("DCCCXCI", 891),
                arguments("DCCCXCII", 892),
                arguments("DCCCXCIII", 893),
                arguments("DCCCXCIV", 894),
                arguments("DCCCXCV", 895),
                arguments("DCCCXCVI", 896),
                arguments("DCCCXCVII", 897),
                arguments("DCCCXCVIII", 898),
                arguments("DCCCXCIX", 899),
                arguments("CM", 900),

                arguments("CMI", 901),
                arguments("CMII", 902),
                arguments("CMIII", 903),
                arguments("CMIV", 904),
                arguments("CMV", 905),
                arguments("CMVI", 906),
                arguments("CMVII", 907),
                arguments("CMVIII", 908),
                arguments("CMIX", 909),
                arguments("CMX", 910),

                arguments("CMXI", 911),
                arguments("CMXII", 912),
                arguments("CMXIII", 913),
                arguments("CMXIV", 914),
                arguments("CMXV", 915),
                arguments("CMXVI", 916),
                arguments("CMXVII", 917),
                arguments("CMXVIII", 918),
                arguments("CMXIX", 919),
                arguments("CMXX", 920),

                arguments("CMXXI", 921),
                arguments("CMXXII", 922),
                arguments("CMXXIII", 923),
                arguments("CMXXIV", 924),
                arguments("CMXXV", 925),
                arguments("CMXXVI", 926),
                arguments("CMXXVII", 927),
                arguments("CMXXVIII", 928),
                arguments("CMXXIX", 929),
                arguments("CMXXX", 930),

                arguments("CMXXXI", 931),
                arguments("CMXXXII", 932),
                arguments("CMXXXIII", 933),
                arguments("CMXXXIV", 934),
                arguments("CMXXXV", 935),
                arguments("CMXXXVI", 936),
                arguments("CMXXXVII", 937),
                arguments("CMXXXVIII", 938),
                arguments("CMXXXIX", 939),
                arguments("CMXL", 940),

                arguments("CMXLI", 941),
                arguments("CMXLII", 942),
                arguments("CMXLIII", 943),
                arguments("CMXLIV", 944),
                arguments("CMXLV", 945),
                arguments("CMXLVI", 946),
                arguments("CMXLVII", 947),
                arguments("CMXLVIII", 948),
                arguments("CMXLIX", 949),
                arguments("CML", 950),

                arguments("CMLI", 951),
                arguments("CMLII", 952),
                arguments("CMLIII", 953),
                arguments("CMLIV", 954),
                arguments("CMLV", 955),
                arguments("CMLVI", 956),
                arguments("CMLVII", 957),
                arguments("CMLVIII", 958),
                arguments("CMLIX", 959),
                arguments("CMLX", 960),

                arguments("CMLXI", 961),
                arguments("CMLXII", 962),
                arguments("CMLXIII", 963),
                arguments("CMLXIV", 964),
                arguments("CMLXV", 965),
                arguments("CMLXVI", 966),
                arguments("CMLXVII", 967),
                arguments("CMLXVIII", 968),
                arguments("CMLXIX", 969),
                arguments("CMLXX", 970),

                arguments("CMLXXI", 971),
                arguments("CMLXXII", 972),
                arguments("CMLXXIII", 973),
                arguments("CMLXXIV", 974),
                arguments("CMLXXV", 975),
                arguments("CMLXXVI", 976),
                arguments("CMLXXVII", 977),
                arguments("CMLXXVIII", 978),
                arguments("CMLXXIX", 979),
                arguments("CMLXXX", 980),

                arguments("CMLXXXI", 981),
                arguments("CMLXXXII", 982),
                arguments("CMLXXXIII", 983),
                arguments("CMLXXXIV", 984),
                arguments("CMLXXXV", 985),
                arguments("CMLXXXVI", 986),
                arguments("CMLXXXVII", 987),
                arguments("CMLXXXVIII", 988),
                arguments("CMLXXXIX", 989),
                arguments("CMXC", 990),

                arguments("CMXCI", 991),
                arguments("CMXCII", 992),
                arguments("CMXCIII", 993),
                arguments("CMXCIV", 994),
                arguments("CMXCV", 995),
                arguments("CMXCVI", 996),
                arguments("CMXCVII", 997),
                arguments("CMXCVIII", 998),
                arguments("CMXCIX", 999),
                arguments("M", 1000),

                arguments("MI", 1001),
                arguments("MIV", 1004),
                arguments("MV", 1005),
                arguments("MVI", 1006),
                arguments("MIX", 1009),
                arguments("MX", 1010),

                arguments("MXX", 1020),
                arguments("MXL", 1040),
                arguments("MXLI", 1041),
                arguments("MXLIV", 1044),
                arguments("MXLV", 1045),
                arguments("MXLVI", 1046),
                arguments("MXLIX", 1049),
                arguments("ML", 1050),
                arguments("MXC", 1090),
                arguments("MC", 1100),
                arguments("MCD", 1400),
                arguments("MD", 1500),
                arguments("MDC", 1600),
                arguments("MDCLXVI", 1666),
                arguments("MCM", 1900),

                arguments("MCMI", 1901),
                arguments("MCMII", 1902),
                arguments("MCMIII", 1903),
                arguments("MCMIV", 1904),
                arguments("MCMV", 1905),
                arguments("MCMVI", 1906),
                arguments("MCMXLIV", 1944),
                arguments("MCMXLIX", 1949),
                arguments("MCML", 1950),

                arguments("MCMXC", 1990),

                arguments("MCMXCI", 1991),
                arguments("MCMXCII", 1992),
                arguments("MCMXCIII", 1993),
                arguments("MCMXCIV", 1994),
                arguments("MCMXCV", 1995),
                arguments("MCMXCVI", 1996),
                arguments("MCMXCVII", 1997),
                arguments("MCMXCVIII", 1998),
                arguments("MCMXCIX", 1999),
                arguments("MM", 2000),
                arguments("MMVIII", 2008)
        );
    }

    @ParameterizedTest
    @ValueSource(strings = {
            "IL", "IC", "ID", "IM",
            "VX", "VL", "VC", "VD", "VM",
            "XD", "XM",
            "LC", "LD", "LM",
            "DM"})
    void whenPassingInvalidSubtractionRomanNumerals_throwException(String input) {
        assertThatThrownBy(() -> underTest.convert(input)).isInstanceOf(IllegalArgumentException.class);
    }

}
